version: '3'
services:
  app:
    build: ./
    ports: 
    - 5000:5000
    volumes:
    - ./:/app
  # db:
  #   restart: always
  #   image: mysql/mysql-server:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: flask_app
  #     MYSQL_USER: docker
  #     MYSQL_PASSWORD: docker
  #     TZ: 'Asia/Tokyo'
  #   volumes:
  #   - ./data_mysql:/var/lib/mysql
  #   ports:
  #   - 3306:3306