"""add AcceptWait

Revision ID: 5bdcabe3db67
Revises: b11827d2c2ea
Create Date: 2024-12-13 19:25:07.849408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdcabe3db67'
down_revision = 'b11827d2c2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accept_wait', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrow_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('will_cancel_at', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key("fk_borrow_borrow_id_id", 'borrow', ['borrow_id'], ['id'])

    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accept_wait_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_accept_wait_accept_wait_id_id", 'accept_wait', ['accept_wait_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.drop_constraint("fk_borrow_borrow_id_id", type_='foreignkey')
        batch_op.drop_column('accept_wait_id')

    with op.batch_alter_table('accept_wait', schema=None) as batch_op:
        batch_op.drop_constraint("fk_accept_wait_accept_wait_id_id", type_='foreignkey')
        batch_op.drop_column('will_cancel_at')
        batch_op.drop_column('borrow_id')

    # ### end Alembic commands ###
